<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 8 Visualising trends | Analyse og visualisering af biologiske datasæt - 2022</title>
  <meta name="description" content="Course materials for Analyse og visualisering af biologiske datasæt 2022" />
  <meta name="generator" content="bookdown 0.25 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 8 Visualising trends | Analyse og visualisering af biologiske datasæt - 2022" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Course materials for Analyse og visualisering af biologiske datasæt 2022" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 Visualising trends | Analyse og visualisering af biologiske datasæt - 2022" />
  
  <meta name="twitter:description" content="Course materials for Analyse og visualisering af biologiske datasæt 2022" />
  

<meta name="author" content="Sarah Rennie" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="forbine-tables-iterations-og-funktioner.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Visualisering kursus</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Grundlæggende R<span></span></a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#inledning-til-kapitel"><i class="fa fa-check"></i><b>1.1</b> Inledning til kapitel<span></span></a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#rstudio"><i class="fa fa-check"></i><b>1.2</b> RStudio<span></span></a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#de-forskellige-vinduer-i-rstudio"><i class="fa fa-check"></i><b>1.2.1</b> De forskellige vinduer i RStudio<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#working-directory"><i class="fa fa-check"></i><b>1.3</b> Working directory<span></span></a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#r-pakker"><i class="fa fa-check"></i><b>1.4</b> R pakker<span></span></a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#hvor-kommer-vores-data-fra"><i class="fa fa-check"></i><b>1.5</b> Hvor kommer vores data fra?<span></span></a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="index.html"><a href="index.html#indbyggede-datasæt"><i class="fa fa-check"></i><b>1.5.1</b> Indbyggede datasæt<span></span></a></li>
<li class="chapter" data-level="1.5.2" data-path="index.html"><a href="index.html#importering-af-data-fra-.txt-fil"><i class="fa fa-check"></i><b>1.5.2</b> Importering af data fra .txt fil<span></span></a></li>
<li class="chapter" data-level="1.5.3" data-path="index.html"><a href="index.html#importering-af-data-fra-excel"><i class="fa fa-check"></i><b>1.5.3</b> Importering af data fra Excel<span></span></a></li>
<li class="chapter" data-level="1.5.4" data-path="index.html"><a href="index.html#kaggle"><i class="fa fa-check"></i><b>1.5.4</b> Kaggle<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#beregninger-i-r"><i class="fa fa-check"></i><b>1.6</b> Beregninger i R<span></span></a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="index.html"><a href="index.html#vectorer"><i class="fa fa-check"></i><b>1.6.1</b> Vectorer<span></span></a></li>
<li class="chapter" data-level="1.6.2" data-path="index.html"><a href="index.html#datatyper"><i class="fa fa-check"></i><b>1.6.2</b> datatyper<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#dataframes"><i class="fa fa-check"></i><b>1.7</b> Dataframes<span></span></a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="index.html"><a href="index.html#delmægder-af-dataframes"><i class="fa fa-check"></i><b>1.7.1</b> Delmægder af dataframes<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#descriptive-statistics"><i class="fa fa-check"></i><b>1.8</b> Descriptive statistics<span></span></a>
<ul>
<li class="chapter" data-level="1.8.1" data-path="index.html"><a href="index.html#simulere-data-fra-den-normale-fordeling"><i class="fa fa-check"></i><b>1.8.1</b> Simulere data fra den normale fordeling<span></span></a></li>
<li class="chapter" data-level="1.8.2" data-path="index.html"><a href="index.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>1.8.2</b> Measures of central tendency<span></span></a></li>
<li class="chapter" data-level="1.8.3" data-path="index.html"><a href="index.html#tapply"><i class="fa fa-check"></i><b>1.8.3</b> <code>tapply()</code><span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#statistike-tester"><i class="fa fa-check"></i><b>1.9</b> Statistike tester<span></span></a>
<ul>
<li class="chapter" data-level="1.9.1" data-path="index.html"><a href="index.html#korrelation"><i class="fa fa-check"></i><b>1.9.1</b> Korrelation<span></span></a></li>
<li class="chapter" data-level="1.9.2" data-path="index.html"><a href="index.html#test-for-uafhængighed-chi-sq-test"><i class="fa fa-check"></i><b>1.9.2</b> Test for uafhængighed (chi-sq test)<span></span></a></li>
<li class="chapter" data-level="1.9.3" data-path="index.html"><a href="index.html#sample-t-test"><i class="fa fa-check"></i><b>1.9.3</b> 1 sample t-test<span></span></a></li>
<li class="chapter" data-level="1.9.4" data-path="index.html"><a href="index.html#sample-t-test-1"><i class="fa fa-check"></i><b>1.9.4</b> 2-sample t-test<span></span></a></li>
<li class="chapter" data-level="1.9.5" data-path="index.html"><a href="index.html#paired-t-test"><i class="fa fa-check"></i><b>1.9.5</b> Paired t-test<span></span></a></li>
<li class="chapter" data-level="1.9.6" data-path="index.html"><a href="index.html#anova-variansanalyse"><i class="fa fa-check"></i><b>1.9.6</b> ANOVA (variansanalyse)<span></span></a></li>
<li class="chapter" data-level="1.9.7" data-path="index.html"><a href="index.html#lineær-regression"><i class="fa fa-check"></i><b>1.9.7</b> Lineær regression<span></span></a></li>
<li class="chapter" data-level="1.9.8" data-path="index.html"><a href="index.html#r-squared-coefficient-of-determination"><i class="fa fa-check"></i><b>1.9.8</b> R-squared coefficient of determination<span></span></a></li>
<li class="chapter" data-level="1.9.9" data-path="index.html"><a href="index.html#antagelser---lineær-regression"><i class="fa fa-check"></i><b>1.9.9</b> Antagelser - lineær regression<span></span></a></li>
<li class="chapter" data-level="1.9.10" data-path="index.html"><a href="index.html#multiple-lineær-regression"><i class="fa fa-check"></i><b>1.9.10</b> Multiple lineær regression<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="index.html"><a href="index.html#problemstillinger"><i class="fa fa-check"></i><b>1.10</b> Problemstillinger<span></span></a>
<ul>
<li class="chapter" data-level="1.10.1" data-path="index.html"><a href="index.html#quiz---basics"><i class="fa fa-check"></i><b>1.10.1</b> Quiz - Basics<span></span></a></li>
<li class="chapter" data-level="1.10.2" data-path="index.html"><a href="index.html#grundlæggende-r"><i class="fa fa-check"></i><b>1.10.2</b> Grundlæggende R<span></span></a></li>
<li class="chapter" data-level="1.10.3" data-path="index.html"><a href="index.html#kort-analyse-med-reaktionstider"><i class="fa fa-check"></i><b>1.10.3</b> Kort analyse med reaktionstider<span></span></a></li>
<li class="chapter" data-level="1.10.4" data-path="index.html"><a href="index.html#ekstra-øvelser-med-statistik-tests"><i class="fa fa-check"></i><b>1.10.4</b> Ekstra øvelser med statistik tests<span></span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="rmarkdown.html"><a href="rmarkdown.html"><i class="fa fa-check"></i><b>2</b> Introduktion til R Markdown<span></span></a>
<ul>
<li class="chapter" data-level="2.1" data-path="rmarkdown.html"><a href="rmarkdown.html#hvad-er-r-markdown"><i class="fa fa-check"></i><b>2.1</b> Hvad er R Markdown?<span></span></a></li>
<li class="chapter" data-level="2.2" data-path="rmarkdown.html"><a href="rmarkdown.html#installere-r-markdown"><i class="fa fa-check"></i><b>2.2</b> Installere R Markdown<span></span></a></li>
<li class="chapter" data-level="2.3" data-path="rmarkdown.html"><a href="rmarkdown.html#videodemonstrationer"><i class="fa fa-check"></i><b>2.3</b> Videodemonstrationer<span></span></a></li>
<li class="chapter" data-level="2.4" data-path="rmarkdown.html"><a href="rmarkdown.html#oprette-et-nyt-dokument-i-r-markdown"><i class="fa fa-check"></i><b>2.4</b> Oprette et nyt dokument i R Markdown<span></span></a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="rmarkdown.html"><a href="rmarkdown.html#yaml"><i class="fa fa-check"></i><b>2.4.1</b> YAML<span></span></a></li>
<li class="chapter" data-level="2.4.2" data-path="rmarkdown.html"><a href="rmarkdown.html#globale-options"><i class="fa fa-check"></i><b>2.4.2</b> Globale options<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="rmarkdown.html"><a href="rmarkdown.html#skrive-baseret-tekst"><i class="fa fa-check"></i><b>2.5</b> Skrive baseret tekst<span></span></a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="rmarkdown.html"><a href="rmarkdown.html#headers"><i class="fa fa-check"></i><b>2.5.1</b> Headers<span></span></a></li>
<li class="chapter" data-level="2.5.2" data-path="rmarkdown.html"><a href="rmarkdown.html#liste"><i class="fa fa-check"></i><b>2.5.2</b> liste<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="rmarkdown.html"><a href="rmarkdown.html#knitte-kode"><i class="fa fa-check"></i><b>2.6</b> Knitte kode<span></span></a></li>
<li class="chapter" data-level="2.7" data-path="rmarkdown.html"><a href="rmarkdown.html#kode-chunks"><i class="fa fa-check"></i><b>2.7</b> Kode chunks<span></span></a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="rmarkdown.html"><a href="rmarkdown.html#et-godt-råd-når-man-arbejder-med-chunks"><i class="fa fa-check"></i><b>2.7.1</b> Et godt råd når man arbejder med chunks<span></span></a></li>
<li class="chapter" data-level="2.7.2" data-path="rmarkdown.html"><a href="rmarkdown.html#chunk-indstillinger"><i class="fa fa-check"></i><b>2.7.2</b> Chunk indstillinger<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="rmarkdown.html"><a href="rmarkdown.html#r-beregninger-indenfor-teksten-i-dokument-inline-code"><i class="fa fa-check"></i><b>2.8</b> R beregninger indenfor teksten i dokument (‘inline code’)<span></span></a></li>
<li class="chapter" data-level="2.9" data-path="rmarkdown.html"><a href="rmarkdown.html#working-directory-1"><i class="fa fa-check"></i><b>2.9</b> Working directory<span></span></a></li>
<li class="chapter" data-level="2.10" data-path="rmarkdown.html"><a href="rmarkdown.html#matematik"><i class="fa fa-check"></i><b>2.10</b> Matematik<span></span></a></li>
<li class="chapter" data-level="2.11" data-path="rmarkdown.html"><a href="rmarkdown.html#problemstillinger-1"><i class="fa fa-check"></i><b>2.11</b> Problemstillinger<span></span></a></li>
<li class="chapter" data-level="2.12" data-path="rmarkdown.html"><a href="rmarkdown.html#færdig-for-i-dag-og-næste-gang"><i class="fa fa-check"></i><b>2.12</b> Færdig for i dag og næste gang<span></span></a></li>
<li class="chapter" data-level="2.13" data-path="rmarkdown.html"><a href="rmarkdown.html#ekstra-links"><i class="fa fa-check"></i><b>2.13</b> Ekstra links<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visual1.html"><a href="visual1.html"><i class="fa fa-check"></i><b>3</b> Visualisering - ggplot2 dag 1<span></span></a>
<ul>
<li class="chapter" data-level="3.1" data-path="visual1.html"><a href="visual1.html#inledning-og-videoer"><i class="fa fa-check"></i><b>3.1</b> Inledning og videoer<span></span></a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="visual1.html"><a href="visual1.html#læringsmålene-for-dag-1"><i class="fa fa-check"></i><b>3.1.1</b> Læringsmålene for dag 1<span></span></a></li>
<li class="chapter" data-level="3.1.2" data-path="visual1.html"><a href="visual1.html#hvad-er-ggplot2"><i class="fa fa-check"></i><b>3.1.2</b> Hvad er <strong>ggplot2</strong>?<span></span></a></li>
<li class="chapter" data-level="3.1.3" data-path="visual1.html"><a href="visual1.html#brugen-af-materialerne"><i class="fa fa-check"></i><b>3.1.3</b> Brugen af materialerne<span></span></a></li>
<li class="chapter" data-level="3.1.4" data-path="visual1.html"><a href="visual1.html#video-ressourcer"><i class="fa fa-check"></i><b>3.1.4</b> Video ressourcer<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="visual1.html"><a href="visual1.html#transition-fra-base-r-til-ggplot2"><i class="fa fa-check"></i><b>3.2</b> Transition fra base R til ggplot2<span></span></a></li>
<li class="chapter" data-level="3.3" data-path="visual1.html"><a href="visual1.html#vores-første-ggplot"><i class="fa fa-check"></i><b>3.3</b> Vores første ggplot<span></span></a></li>
<li class="chapter" data-level="3.4" data-path="visual1.html"><a href="visual1.html#lidt-om-ggplot2"><i class="fa fa-check"></i><b>3.4</b> Lidt om ggplot2<span></span></a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="visual1.html"><a href="visual1.html#syntax"><i class="fa fa-check"></i><b>3.4.1</b> Syntax<span></span></a></li>
<li class="chapter" data-level="3.4.2" data-path="visual1.html"><a href="visual1.html#hvad-betyder-egentlig-grammar-of-graphics"><i class="fa fa-check"></i><b>3.4.2</b> Hvad betyder egentlig grammar of graphics?<span></span></a></li>
<li class="chapter" data-level="3.4.3" data-path="visual1.html"><a href="visual1.html#globale-versus-lokale-æstetik"><i class="fa fa-check"></i><b>3.4.3</b> Globale versus lokale æstetik<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="visual1.html"><a href="visual1.html#specificere-etiketter-og-titel"><i class="fa fa-check"></i><b>3.5</b> Specificere etiketter og titel<span></span></a></li>
<li class="chapter" data-level="3.6" data-path="visual1.html"><a href="visual1.html#ændre-farver"><i class="fa fa-check"></i><b>3.6</b> Ændre farver<span></span></a></li>
<li class="chapter" data-level="3.7" data-path="visual1.html"><a href="visual1.html#ændre-tema"><i class="fa fa-check"></i><b>3.7</b> Ændre tema<span></span></a></li>
<li class="chapter" data-level="3.8" data-path="visual1.html"><a href="visual1.html#forskellige-geoms"><i class="fa fa-check"></i><b>3.8</b> Forskellige geoms<span></span></a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="visual1.html"><a href="visual1.html#boxplot-geom_box"><i class="fa fa-check"></i><b>3.8.1</b> Boxplot (<code>geom_box</code>)<span></span></a></li>
<li class="chapter" data-level="3.8.2" data-path="visual1.html"><a href="visual1.html#barplot-geom_bar"><i class="fa fa-check"></i><b>3.8.2</b> Barplot (<code>geom_bar</code>)<span></span></a></li>
<li class="chapter" data-level="3.8.3" data-path="visual1.html"><a href="visual1.html#histogram-geom_histogram"><i class="fa fa-check"></i><b>3.8.3</b> Histogram (<code>geom_histogram</code>)<span></span></a></li>
<li class="chapter" data-level="3.8.4" data-path="visual1.html"><a href="visual1.html#density-geom_density"><i class="fa fa-check"></i><b>3.8.4</b> Density (<code>geom_density</code>)<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="visual1.html"><a href="visual1.html#troubleshooting"><i class="fa fa-check"></i><b>3.9</b> Troubleshooting<span></span></a></li>
<li class="chapter" data-level="3.10" data-path="visual1.html"><a href="visual1.html#problemstillinger-2"><i class="fa fa-check"></i><b>3.10</b> Problemstillinger<span></span></a></li>
<li class="chapter" data-level="3.11" data-path="visual1.html"><a href="visual1.html#næste-gang"><i class="fa fa-check"></i><b>3.11</b> Næste gang<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="visual2.html"><a href="visual2.html"><i class="fa fa-check"></i><b>4</b> Visualisering - ggplot2 dag 2<span></span></a>
<ul>
<li class="chapter" data-level="4.1" data-path="visual2.html"><a href="visual2.html#indledning-og-videoer"><i class="fa fa-check"></i><b>4.1</b> Indledning og videoer<span></span></a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="visual2.html"><a href="visual2.html#læringsmålene"><i class="fa fa-check"></i><b>4.1.1</b> Læringsmålene<span></span></a></li>
<li class="chapter" data-level="4.1.2" data-path="visual2.html"><a href="visual2.html#video-ressourcer-1"><i class="fa fa-check"></i><b>4.1.2</b> Video ressourcer<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="visual2.html"><a href="visual2.html#koordinat-systemer"><i class="fa fa-check"></i><b>4.2</b> Koordinat systemer<span></span></a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="visual2.html"><a href="visual2.html#zoom-coord_cartesian-expand_limits"><i class="fa fa-check"></i><b>4.2.1</b> Zoom (<code>coord_cartesian()</code>, <code>expand_limits()</code>)<span></span></a></li>
<li class="chapter" data-level="4.2.2" data-path="visual2.html"><a href="visual2.html#transformering-af-akserne---log-sqrt-osv-scale_x_continuous."><i class="fa fa-check"></i><b>4.2.2</b> Transformering af akserne - log, sqrt osv (<code>scale_x_continuous</code>).<span></span></a></li>
<li class="chapter" data-level="4.2.3" data-path="visual2.html"><a href="visual2.html#flip-coordinates-coord_flip"><i class="fa fa-check"></i><b>4.2.3</b> Flip coordinates (<code>coord_flip</code>)<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="visual2.html"><a href="visual2.html#mere-om-farver-og-punkt-former"><i class="fa fa-check"></i><b>4.3</b> Mere om farver og punkt former<span></span></a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="visual2.html"><a href="visual2.html#automatisk-farver"><i class="fa fa-check"></i><b>4.3.1</b> Automatisk farver<span></span></a></li>
<li class="chapter" data-level="4.3.2" data-path="visual2.html"><a href="visual2.html#manuelle-farver"><i class="fa fa-check"></i><b>4.3.2</b> Manuelle farver<span></span></a></li>
<li class="chapter" data-level="4.3.3" data-path="visual2.html"><a href="visual2.html#punkt-former"><i class="fa fa-check"></i><b>4.3.3</b> Punkt former<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="visual2.html"><a href="visual2.html#annotations-geom_text"><i class="fa fa-check"></i><b>4.4</b> Annotations (<code>geom_text</code>)<span></span></a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="visual2.html"><a href="visual2.html#tilføje-labeller-direkte-på-plottet."><i class="fa fa-check"></i><b>4.4.1</b> Tilføje labeller direkte på plottet.<span></span></a></li>
<li class="chapter" data-level="4.4.2" data-path="visual2.html"><a href="visual2.html#pakken-ggrepel-for-at-tilføje-tekst-labeller"><i class="fa fa-check"></i><b>4.4.2</b> Pakken <code>ggrepel</code> for at tilføje tekst labeller<span></span></a></li>
<li class="chapter" data-level="4.4.3" data-path="visual2.html"><a href="visual2.html#tilføje-rektangler-i-regioner-af-interesse-annotate"><i class="fa fa-check"></i><b>4.4.3</b> Tilføje rektangler i regioner af interesse (<code>annotate</code>)<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="visual2.html"><a href="visual2.html#adskille-plots-med-facets-facet_gridfacet_wrap"><i class="fa fa-check"></i><b>4.5</b> Adskille plots med facets (<code>facet_grid</code>/<code>facet_wrap</code>)<span></span></a></li>
<li class="chapter" data-level="4.6" data-path="visual2.html"><a href="visual2.html#gemme-dit-plot"><i class="fa fa-check"></i><b>4.6</b> Gemme dit plot<span></span></a></li>
<li class="chapter" data-level="4.7" data-path="visual2.html"><a href="visual2.html#problemstillinger-3"><i class="fa fa-check"></i><b>4.7</b> Problemstillinger<span></span></a></li>
<li class="chapter" data-level="4.8" data-path="visual2.html"><a href="visual2.html#ekstra-links-1"><i class="fa fa-check"></i><b>4.8</b> Ekstra links<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>5</b> Bearbejdning dag 1<span></span></a>
<ul>
<li class="chapter" data-level="5.1" data-path="data.html"><a href="data.html#inledning-og-læringsmålene"><i class="fa fa-check"></i><b>5.1</b> Inledning og læringsmålene<span></span></a></li>
<li class="chapter" data-level="5.2" data-path="data.html"><a href="data.html#video-ressourcer-2"><i class="fa fa-check"></i><b>5.2</b> Video ressourcer<span></span></a></li>
<li class="chapter" data-level="5.3" data-path="data.html"><a href="data.html#hvad-er-tidyverse"><i class="fa fa-check"></i><b>5.3</b> Hvad er Tidyverse?<span></span></a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="data.html"><a href="data.html#princippen-med-tidy-data"><i class="fa fa-check"></i><b>5.3.1</b> Princippen med ‘tidy data’<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="data.html"><a href="data.html#lidt-om-tibbles"><i class="fa fa-check"></i><b>5.4</b> Lidt om <code>tibbles</code><span></span></a></li>
<li class="chapter" data-level="5.5" data-path="data.html"><a href="data.html#transition-fra-base-til-tidyverse"><i class="fa fa-check"></i><b>5.5</b> Transition fra base til tidyverse<span></span></a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="data.html"><a href="data.html#om-titanic-datasæt"><i class="fa fa-check"></i><b>5.5.1</b> Om <strong>Titanic</strong> datasæt<span></span></a></li>
<li class="chapter" data-level="5.5.2" data-path="data.html"><a href="data.html#titanic-oprydning"><i class="fa fa-check"></i><b>5.5.2</b> Titanic: oprydning<span></span></a></li>
<li class="chapter" data-level="5.5.3" data-path="data.html"><a href="data.html#pipe"><i class="fa fa-check"></i><b>5.5.3</b> Pipe<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="data.html"><a href="data.html#bearbejdning-af-data-dplyr"><i class="fa fa-check"></i><b>5.6</b> Bearbejdning af data: <code>dplyr</code><span></span></a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="data.html"><a href="data.html#dplyr-verbs-select"><i class="fa fa-check"></i><b>5.6.1</b> dplyr verbs: <code>select()</code><span></span></a></li>
<li class="chapter" data-level="5.6.2" data-path="data.html"><a href="data.html#dplyr-verbs-filter"><i class="fa fa-check"></i><b>5.6.2</b> dplyr verbs: <code>filter()</code><span></span></a></li>
<li class="chapter" data-level="5.6.3" data-path="data.html"><a href="data.html#comparitiver-reference"><i class="fa fa-check"></i><b>5.6.3</b> Comparitiver reference<span></span></a></li>
<li class="chapter" data-level="5.6.4" data-path="data.html"><a href="data.html#kombinere-filter-og-select"><i class="fa fa-check"></i><b>5.6.4</b> Kombinere <code>filter()</code> og <code>select()</code><span></span></a></li>
<li class="chapter" data-level="5.6.5" data-path="data.html"><a href="data.html#dplyr-verbs-mutate"><i class="fa fa-check"></i><b>5.6.5</b> dplyr verbs: <code>mutate()</code><span></span></a></li>
<li class="chapter" data-level="5.6.6" data-path="data.html"><a href="data.html#rename"><i class="fa fa-check"></i><b>5.6.6</b> <code>rename()</code><span></span></a></li>
<li class="chapter" data-level="5.6.7" data-path="data.html"><a href="data.html#dplyr-verbs-recode"><i class="fa fa-check"></i><b>5.6.7</b> dplyr verbs: <code>recode()</code><span></span></a></li>
<li class="chapter" data-level="5.6.8" data-path="data.html"><a href="data.html#dplyr-verbs-arrange"><i class="fa fa-check"></i><b>5.6.8</b> dplyr verbs: <code>arrange()</code><span></span></a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="data.html"><a href="data.html#visualisering-bruge-som-input-i-ggplot2"><i class="fa fa-check"></i><b>5.7</b> Visualisering: bruge som input i ggplot2<span></span></a></li>
<li class="chapter" data-level="5.8" data-path="data.html"><a href="data.html#problemstillinger-4"><i class="fa fa-check"></i><b>5.8</b> Problemstillinger<span></span></a></li>
<li class="chapter" data-level="5.9" data-path="data.html"><a href="data.html#kommentarer"><i class="fa fa-check"></i><b>5.9</b> Kommentarer<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html"><i class="fa fa-check"></i><b>6</b> Bearbejdning dag 2<span></span></a>
<ul>
<li class="chapter" data-level="6.1" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#indledning-og-læringsmålene"><i class="fa fa-check"></i><b>6.1</b> Indledning og læringsmålene<span></span></a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#læringsmålene-1"><i class="fa fa-check"></i><b>6.1.1</b> Læringsmålene<span></span></a></li>
<li class="chapter" data-level="6.1.2" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#videoer"><i class="fa fa-check"></i><b>6.1.2</b> Videoer<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#dplyr-group_by-med-summarise"><i class="fa fa-check"></i><b>6.2</b> dplyr: <code>group_by()</code> med <code>summarise()</code><span></span></a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#reference-af-summary-funktioner"><i class="fa fa-check"></i><b>6.2.1</b> Reference af <code>summary()</code> funktioner<span></span></a></li>
<li class="chapter" data-level="6.2.2" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#flere-summary-statistic-på-én-gang"><i class="fa fa-check"></i><b>6.2.2</b> Flere summary statistic på én gang<span></span></a></li>
<li class="chapter" data-level="6.2.3" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#mere-kompliceret-group_by"><i class="fa fa-check"></i><b>6.2.3</b> Mere kompliceret <code>group_by()</code><span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#tidyr-pakke---wide-og-long-data"><i class="fa fa-check"></i><b>6.3</b> Tidyr pakke - Wide og Long data<span></span></a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#tidyr-pakke---oversigt"><i class="fa fa-check"></i><b>6.3.1</b> Tidyr pakke - oversigt<span></span></a></li>
<li class="chapter" data-level="6.3.2" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#wide---long-med-pivot_longer"><i class="fa fa-check"></i><b>6.3.2</b> Wide -&gt; Long med <code>pivot_longer()</code><span></span></a></li>
<li class="chapter" data-level="6.3.3" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#separate"><i class="fa fa-check"></i><b>6.3.3</b> <code>separate()</code><span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#eksempel-titanic-summary-statistics"><i class="fa fa-check"></i><b>6.4</b> Eksempel: Titanic summary statistics<span></span></a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#demonstration-af-pivot_wider"><i class="fa fa-check"></i><b>6.4.1</b> Demonstration af <code>pivot_wider()</code><span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#tilføje-sample-oplysninger-med-left_join"><i class="fa fa-check"></i><b>6.5</b> Tilføje sample oplysninger med <code>left_join()</code><span></span></a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#fuktionen-left_join-fra-dplyr-pakken"><i class="fa fa-check"></i><b>6.5.1</b> Fuktionen <code>left_join()</code> fra dplyr-pakken<span></span></a></li>
<li class="chapter" data-level="6.5.2" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#anvende-left_join-for-vores-fiktiv-dataset."><i class="fa fa-check"></i><b>6.5.2</b> Anvende <code>left_join()</code> for vores fiktiv dataset.<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#problemstillinger-5"><i class="fa fa-check"></i><b>6.6</b> Problemstillinger<span></span></a></li>
<li class="chapter" data-level="6.7" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#opgave-fredag-workshop-om-tidyverse"><i class="fa fa-check"></i><b>6.7</b> Opgave (fredag workshop om tidyverse)<span></span></a></li>
<li class="chapter" data-level="6.8" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#ekstra-links-2"><i class="fa fa-check"></i><b>6.8</b> Ekstra links<span></span></a></li>
<li class="chapter" data-level="6.9" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#sidste-kommentarer"><i class="fa fa-check"></i><b>6.9</b> Sidste kommentarer<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="forbine-tables-iterations-og-funktioner.html"><a href="forbine-tables-iterations-og-funktioner.html"><i class="fa fa-check"></i><b>7</b> Forbine tables, iterations og funktioner<span></span></a>
<ul>
<li class="chapter" data-level="7.1" data-path="forbine-tables-iterations-og-funktioner.html"><a href="forbine-tables-iterations-og-funktioner.html#inledning-og-læringsmålene-1"><i class="fa fa-check"></i><b>7.1</b> Inledning og læringsmålene<span></span></a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="forbine-tables-iterations-og-funktioner.html"><a href="forbine-tables-iterations-og-funktioner.html#læringsmålene-2"><i class="fa fa-check"></i><b>7.1.1</b> Læringsmålene<span></span></a></li>
<li class="chapter" data-level="7.1.2" data-path="forbine-tables-iterations-og-funktioner.html"><a href="forbine-tables-iterations-og-funktioner.html#introduktion-til-chapter"><i class="fa fa-check"></i><b>7.1.2</b> Introduktion til Chapter<span></span></a></li>
<li class="chapter" data-level="7.1.3" data-path="forbine-tables-iterations-og-funktioner.html"><a href="forbine-tables-iterations-og-funktioner.html#video-ressourcer-3"><i class="fa fa-check"></i><b>7.1.3</b> Video ressourcer<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="forbine-tables-iterations-og-funktioner.html"><a href="forbine-tables-iterations-og-funktioner.html#iterativ-processer-med-map-fuktioner"><i class="fa fa-check"></i><b>7.2</b> Iterativ processer med <code>map()</code> fuktioner<span></span></a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="forbine-tables-iterations-og-funktioner.html"><a href="forbine-tables-iterations-og-funktioner.html#introduktion-til-map-funktioner"><i class="fa fa-check"></i><b>7.2.1</b> Introduktion til <code>map()</code> funktioner<span></span></a></li>
<li class="chapter" data-level="7.2.2" data-path="forbine-tables-iterations-og-funktioner.html"><a href="forbine-tables-iterations-og-funktioner.html#reference-for-the-different-map-functions"><i class="fa fa-check"></i><b>7.2.2</b> Reference for the different map functions<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="forbine-tables-iterations-og-funktioner.html"><a href="forbine-tables-iterations-og-funktioner.html#custom-functions"><i class="fa fa-check"></i><b>7.3</b> Custom functions<span></span></a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="forbine-tables-iterations-og-funktioner.html"><a href="forbine-tables-iterations-og-funktioner.html#simple-functions"><i class="fa fa-check"></i><b>7.3.1</b> Simple functions<span></span></a></li>
<li class="chapter" data-level="7.3.2" data-path="forbine-tables-iterations-og-funktioner.html"><a href="forbine-tables-iterations-og-funktioner.html#custom-functions-with-mapping"><i class="fa fa-check"></i><b>7.3.2</b> Custom functions with mapping<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="forbine-tables-iterations-og-funktioner.html"><a href="forbine-tables-iterations-og-funktioner.html#nesting-nest"><i class="fa fa-check"></i><b>7.4</b> Nesting <code>nest()</code><span></span></a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="forbine-tables-iterations-og-funktioner.html"><a href="forbine-tables-iterations-og-funktioner.html#anvende-map-med-nested-data"><i class="fa fa-check"></i><b>7.4.1</b> Anvende map() med nested data<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="forbine-tables-iterations-og-funktioner.html"><a href="forbine-tables-iterations-og-funktioner.html#problemstillinger-6"><i class="fa fa-check"></i><b>7.5</b> Problemstillinger<span></span></a></li>
<li class="chapter" data-level="7.6" data-path="forbine-tables-iterations-og-funktioner.html"><a href="forbine-tables-iterations-og-funktioner.html#ekstra-notater-og-næste-gang"><i class="fa fa-check"></i><b>7.6</b> Ekstra notater og næste gang<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="visualising-trends.html"><a href="visualising-trends.html"><i class="fa fa-check"></i><b>8</b> Visualising trends<span></span></a>
<ul>
<li class="chapter" data-level="8.1" data-path="visualising-trends.html"><a href="visualising-trends.html#indledning-og-læringsmålene-1"><i class="fa fa-check"></i><b>8.1</b> Indledning og læringsmålene<span></span></a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="visualising-trends.html"><a href="visualising-trends.html#læringsmålene-3"><i class="fa fa-check"></i><b>8.1.1</b> Læringsmålene<span></span></a></li>
<li class="chapter" data-level="8.1.2" data-path="visualising-trends.html"><a href="visualising-trends.html#introduktion-til-chapter-1"><i class="fa fa-check"></i><b>8.1.2</b> Introduktion til chapter<span></span></a></li>
<li class="chapter" data-level="8.1.3" data-path="visualising-trends.html"><a href="visualising-trends.html#video-ressourcer-4"><i class="fa fa-check"></i><b>8.1.3</b> Video ressourcer<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="visualising-trends.html"><a href="visualising-trends.html#nest-og-map-eksempel-med-korrelation"><i class="fa fa-check"></i><b>8.2</b> <code>nest()</code> og <code>map()</code>: eksempel med korrelation<span></span></a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="visualising-trends.html"><a href="visualising-trends.html#korrelation-analyse-i-r"><i class="fa fa-check"></i><b>8.2.1</b> Korrelation analyse i R<span></span></a></li>
<li class="chapter" data-level="8.2.2" data-path="visualising-trends.html"><a href="visualising-trends.html#korrelation-over-flere-datasæt-på-en-gang"><i class="fa fa-check"></i><b>8.2.2</b> Korrelation over flere datasæt på en gang<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="visualising-trends.html"><a href="visualising-trends.html#visualisering-af-lineær-regression-med-ggplot2"><i class="fa fa-check"></i><b>8.3</b> Visualisering af lineær regression med ggplot2<span></span></a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="visualising-trends.html"><a href="visualising-trends.html#lineær-trends"><i class="fa fa-check"></i><b>8.3.1</b> Lineær trends<span></span></a></li>
<li class="chapter" data-level="8.3.2" data-path="visualising-trends.html"><a href="visualising-trends.html#plotting-lineær-trend-lines-with-geom_smooth"><i class="fa fa-check"></i><b>8.3.2</b> plotting lineær trend lines with <code>geom_smooth()</code><span></span></a></li>
<li class="chapter" data-level="8.3.3" data-path="visualising-trends.html"><a href="visualising-trends.html#plotting-multiple-lineær-trend-lines-with-geom_smooth"><i class="fa fa-check"></i><b>8.3.3</b> plotting multiple lineær trend lines with <code>geom_smooth()</code><span></span></a></li>
<li class="chapter" data-level="8.3.4" data-path="visualising-trends.html"><a href="visualising-trends.html#plot-trends-med-methodloess-i-ggplot."><i class="fa fa-check"></i><b>8.3.4</b> Plot trends med <code>method=="loess"</code> i ggplot.<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="visualising-trends.html"><a href="visualising-trends.html#plot-linear-regresion-estimates"><i class="fa fa-check"></i><b>8.4</b> Plot linear regresion estimates<span></span></a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="visualising-trends.html"><a href="visualising-trends.html#iteratively-estimating-multiple-trends"><i class="fa fa-check"></i><b>8.4.1</b> Iteratively estimating multiple trends<span></span></a></li>
<li class="chapter" data-level="8.4.2" data-path="visualising-trends.html"><a href="visualising-trends.html#lave-og-tilføje-labels-til-dit-regression-plot"><i class="fa fa-check"></i><b>8.4.2</b> Lave og tilføje labels til dit regression plot<span></span></a></li>
<li class="chapter" data-level="8.4.3" data-path="visualising-trends.html"><a href="visualising-trends.html#case_when-adding-bar-plot-text"><i class="fa fa-check"></i><b>8.4.3</b> <code>case_when()</code>: adding bar plot text<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="visualising-trends.html"><a href="visualising-trends.html#problemstillinger-7"><i class="fa fa-check"></i><b>8.5</b> Problemstillinger<span></span></a></li>
<li class="chapter" data-level="8.6" data-path="visualising-trends.html"><a href="visualising-trends.html#næste-uge"><i class="fa fa-check"></i><b>8.6</b> Næste uge<span></span></a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analyse og visualisering af biologiske datasæt - 2022</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="visualising-trends" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Chapter 8</span> Visualising trends<a href="visualising-trends.html#visualising-trends" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><img src="plots/hex-tidyverse.png" width="15%" /></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="visualising-trends.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load packages</span></span>
<span id="cb1-2"><a href="visualising-trends.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="visualising-trends.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>FALSE Warning: package &#39;tidyr&#39; was built under R version 4.0.5</code></pre>
<pre><code>FALSE Warning: package &#39;readr&#39; was built under R version 4.0.5</code></pre>
<pre><code>FALSE Warning: package &#39;dplyr&#39; was built under R version 4.0.5</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="visualising-trends.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb5-2"><a href="visualising-trends.html#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span></code></pre></div>
<pre><code>FALSE Warning: package &#39;broom&#39; was built under R version 4.0.5</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="visualising-trends.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glue)</span></code></pre></div>
<pre><code>FALSE Warning: package &#39;glue&#39; was built under R version 4.0.5</code></pre>
<div id="indledning-og-læringsmålene-1" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Indledning og læringsmålene<a href="visualising-trends.html#indledning-og-læringsmålene-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="læringsmålene-3" class="section level3 hasAnchor" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> Læringsmålene<a href="visualising-trends.html#læringsmålene-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>I skal være i stand til at</p>
<ul>
<li>Anvende <code>nest()</code> og <code>map()</code> strukturen til at gentage en korrelation analyse over flere forskellige datasæt.</li>
<li>Bruge <code>ggplot</code> funktion <code>geom_smooth()</code> til at visualisere lineær regression eller loess trend linjer.</li>
<li>Kombinere <code>map()</code> og <code>lm()</code> til at beregne regression statistike for flere lineær regression modeller og tilføje dem til plottet til at gøre det mere informativ.</li>
</ul>
</div>
<div id="introduktion-til-chapter-1" class="section level3 hasAnchor" number="8.1.2">
<h3><span class="header-section-number">8.1.2</span> Introduktion til chapter<a href="visualising-trends.html#introduktion-til-chapter-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>I dette chapter demonstranter jeg hvordan man anvende den <code>nest()</code> og <code>map()</code> struktur som vi så sidste gange til at lave statistiske analyser med korrelation og lineær regression. Vi lærer hvordan vi kan visualisere trends og korrelations og tilføj relevante statistikker til plots til at gøre dem endnu mere informativ.</p>
</div>
<div id="video-ressourcer-4" class="section level3 hasAnchor" number="8.1.3">
<h3><span class="header-section-number">8.1.3</span> Video ressourcer<a href="visualising-trends.html#video-ressourcer-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>(OBS: kunne desværre ikke nå videoerne til i dag pga. forkølelse/travlhed men kan eventuelle lave dem senere hvis der er efterspørgsel)</p>
<ul>
<li>Video 0: Korrelation koefficient med <code>nest()</code> og <code>map()</code></li>
<li>Video 1: Lineær regression linjer med ggplot2</li>
<li>Video 2: Lineær regression med <code>nest()</code> og <code>map()</code></li>
<li>Video 3: Tilføj labels med <code>lm()</code> statistik på plottet</li>
</ul>
</div>
</div>
<div id="nest-og-map-eksempel-med-korrelation" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> <code>nest()</code> og <code>map()</code>: eksempel med korrelation<a href="visualising-trends.html#nest-og-map-eksempel-med-korrelation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Vi kigger på korrelation analyse først men gentage samme struktur med <code>nest()</code> og <code>map()</code> når vi gennemgå lineær regression.</p>
<div id="korrelation-analyse-i-r" class="section level3 hasAnchor" number="8.2.1">
<h3><span class="header-section-number">8.2.1</span> Korrelation analyse i R<a href="visualising-trends.html#korrelation-analyse-i-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Man kan lave en korrelation analyse i R ved at anvende <code>cor.test()</code>. For eksempel, forestille os at vi gerne vil finde ud af korrelationen mellem gc content (variablen <code>gc</code>) og genes (variablen <code>genes</code>) for de data <code>eukaryotes</code> fra sidste lektion. Vi plotter en histogram og beslutter os for at lave korrelation mellem <code>gc</code> og den transformerede variable <code>log10(genes)</code>.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="visualising-trends.html#cb9-1" aria-hidden="true" tabindex="-1"></a>eukaryotes <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="visualising-trends.html#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log10_size_mb =</span> <span class="fu">log10</span>(size_mb)) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="visualising-trends.html#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(log10_size_mb,gc) <span class="sc">%&gt;%</span> </span>
<span id="cb9-4"><a href="visualising-trends.html#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb9-5"><a href="visualising-trends.html#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>value,<span class="at">fill=</span>name)) <span class="sc">+</span> </span>
<span id="cb9-6"><a href="visualising-trends.html#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">40</span>,<span class="at">colour=</span><span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb9-7"><a href="visualising-trends.html#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>name,<span class="at">scales=</span><span class="st">&quot;free&quot;</span>) <span class="sc">+</span></span>
<span id="cb9-8"><a href="visualising-trends.html#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 388 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="visualisering_22_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Vi mistænkter, at der kan være nogle sub-struturer indenfor de data - for eksempel over de forskellige organismer grupper i variablen <code>Group</code>. Vi benytter alligevel <code>cor.test()</code> til at teste for korrelation mellem <code>gc</code> og <code>log10(size_mb)</code> over hele datasæt:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="visualising-trends.html#cb11-1" aria-hidden="true" tabindex="-1"></a>my_cor_test <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(eukaryotes<span class="sc">$</span>gc,<span class="fu">log10</span>(eukaryotes<span class="sc">$</span>size_mb))</span>
<span id="cb11-2"><a href="visualising-trends.html#cb11-2" aria-hidden="true" tabindex="-1"></a>my_cor_test</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  eukaryotes$gc and log10(eukaryotes$size_mb)
## t = -15.678, df = 11118, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.1652066 -0.1288369
## sample estimates:
##        cor 
## -0.1470715</code></pre>
<p>Her vil jeg også gerne introducerer en funktion der hedder <code>glance()</code> som findes i R-pakken <code>broom</code>. Funktionen <code>glance()</code> anvendes til at tage den output fra en statistiske test (fk. <code>cor.test()</code>) og lave det om til et <strong>tidy</strong> dataramme. Det gøre det nemmere for eksempel til at lave et plot, eller samler op statistikker fra forskellige tests.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="visualising-trends.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb13-2"><a href="visualising-trends.html#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(my_cor_test)</span></code></pre></div>
<pre><code>FALSE # A tibble: 1 × 8
FALSE   estimate statistic  p.value parameter conf.low conf.high method    alternative
FALSE      &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;int&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;      
FALSE 1   -0.147     -15.7 8.25e-55     11118   -0.165    -0.129 Pearson&#39;… two.sided</code></pre>
<p>Vi kan se at over hele datasæt, er der en signifikant negativ korrelation (estimate -0.147 og p-værdi 8.25054^{-55}) mellem de to variabler, men vi er dog stadig mistænksom overfor eventuelle forskelligheder blandt de fem grupper fra variablen <code>group</code>.</p>
<p>Vi vil gerne gentage vores nalyse for hver af de fem grupper fra <code>group</code>. En god tilgang til at undersøge det er at bruge den ramme med <code>group_by()</code> og <code>nest()</code> som vi lært sidste gange.</p>
</div>
<div id="korrelation-over-flere-datasæt-på-en-gang" class="section level3 hasAnchor" number="8.2.2">
<h3><span class="header-section-number">8.2.2</span> Korrelation over flere datasæt på en gang<a href="visualising-trends.html#korrelation-over-flere-datasæt-på-en-gang" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Lad os først tjekke fordelingen af de to variabler opdelt efter variablen <code>group</code>. Bemærk at når de to variabler er i forskellige kolonner er vi nødt til at først få vores data i long form med <code>pivot_longer()</code>.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="visualising-trends.html#cb15-1" aria-hidden="true" tabindex="-1"></a>eukaryotes <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="visualising-trends.html#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log10_size_mb =</span> <span class="fu">log10</span>(size_mb)) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="visualising-trends.html#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(log10_size_mb,gc,group) <span class="sc">%&gt;%</span> </span>
<span id="cb15-4"><a href="visualising-trends.html#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>group) <span class="sc">%&gt;%</span></span>
<span id="cb15-5"><a href="visualising-trends.html#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>value,<span class="at">fill=</span>group)) <span class="sc">+</span> </span>
<span id="cb15-6"><a href="visualising-trends.html#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">40</span>,<span class="at">alpha=</span><span class="fl">0.5</span>,<span class="at">colour=</span><span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb15-7"><a href="visualising-trends.html#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">&quot;Set1&quot;</span>) <span class="sc">+</span></span>
<span id="cb15-8"><a href="visualising-trends.html#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>name,<span class="at">scales=</span><span class="st">&quot;free&quot;</span>) <span class="sc">+</span></span>
<span id="cb15-9"><a href="visualising-trends.html#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 388 rows containing non-finite values (stat_bin).</code></pre>
<p><img src="visualisering_22_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Vi kan se, at der er forskelligheder blandt de fem grupper og der kan forekommer forskellige sammenhænge mellem de to variabler. Vi benytter i følgende den <code>group_by()</code> + <code>nest()</code> ramme som blev introducerede sidste lektion.</p>
<p><strong>Definere korrelation funktion</strong></p>
<p>Lad os definere den korrelation test mellem <code>gc</code> og <code>size_mb</code> i en funktion:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="visualising-trends.html#cb17-1" aria-hidden="true" tabindex="-1"></a>cor_test <span class="ot">&lt;-</span> <span class="er">~</span><span class="fu">cor.test</span>(.x<span class="sc">$</span>gc,<span class="fu">log10</span>(.x<span class="sc">$</span>size_mb))</span></code></pre></div>
<p>Husk:</p>
<ul>
<li>Brug <code>~</code> lige i starten for at fortælle R, at vi arbejde med en funktion.</li>
<li>Specificer det indiv datasæt indenfor <code>cor.test()</code> med <code>.x</code> (husk at <code>map()</code> her fungere over en list af datasæt, så indenfor et datasæt specificerer
vi kolonner <code>gc</code> og <code>size_mb</code> ved <code>.x$gc</code> og <code>.x$size_mb</code>).</li>
</ul>
<p>Vi vil gerne få statistikker fra <code>cor.test()</code> i en pænt form så vi tilføjer <code>glance()</code> i funktionen:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="visualising-trends.html#cb18-1" aria-hidden="true" tabindex="-1"></a>cor_test <span class="ot">&lt;-</span> <span class="er">~</span><span class="fu">cor.test</span>(.x<span class="sc">$</span>gc,<span class="fu">log10</span>(.x<span class="sc">$</span>size_mb)) <span class="sc">%&gt;%</span> <span class="fu">glance</span>()</span></code></pre></div>
<p><strong>Benytte <code>group_by()</code> + <code>nest()</code></strong></p>
<p>For at lave et <code>cor.test()</code> til hver af de fem grupper i variablen <code>group()</code>, skal vi først anvende <code>nest()</code>:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="visualising-trends.html#cb19-1" aria-hidden="true" tabindex="-1"></a>eukaryotes_nest <span class="ot">&lt;-</span> eukaryotes <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="visualising-trends.html#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(group) <span class="sc">%&gt;%</span> </span>
<span id="cb19-3"><a href="visualising-trends.html#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>()</span>
<span id="cb19-4"><a href="visualising-trends.html#cb19-4" aria-hidden="true" tabindex="-1"></a>eukaryotes_nest</span></code></pre></div>
<pre><code>## # A tibble: 5 × 2
## # Groups:   group [5]
##   group    data                 
##   &lt;chr&gt;    &lt;list&gt;               
## 1 Other    &lt;tibble [51 × 18]&gt;   
## 2 Protists &lt;tibble [888 × 18]&gt;  
## 3 Plants   &lt;tibble [1,304 × 18]&gt;
## 4 Fungi    &lt;tibble [6,064 × 18]&gt;
## 5 Animals  &lt;tibble [3,201 × 18]&gt;</code></pre>
<p>Vi har fået vores fem sub-datasæt i en list der hedder <code>data</code>.</p>
<p><strong>Bruge map() på de nested datasæt</strong></p>
<p>Nu lad os køre vores funktion på den nested data. Vi bruger <code>map()</code> til at lave samme funktion for hver af de fem datasæt. Vi bruger <code>map</code> indenfor <code>mutate</code> til at lave en ny kolon der hedder <code>test_stats</code>, hvor resultaterne for hver af de fem tests kan lagres.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="visualising-trends.html#cb21-1" aria-hidden="true" tabindex="-1"></a>eukaryotes_cor <span class="ot">&lt;-</span> eukaryotes_nest <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="visualising-trends.html#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb21-3"><a href="visualising-trends.html#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">test_stats=</span><span class="fu">map</span>(data,cor_test),</span>
<span id="cb21-4"><a href="visualising-trends.html#cb21-4" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb21-5"><a href="visualising-trends.html#cb21-5" aria-hidden="true" tabindex="-1"></a>eukaryotes_cor</span></code></pre></div>
<pre><code>## # A tibble: 5 × 3
## # Groups:   group [5]
##   group    data                  test_stats      
##   &lt;chr&gt;    &lt;list&gt;                &lt;list&gt;          
## 1 Other    &lt;tibble [51 × 18]&gt;    &lt;tibble [1 × 8]&gt;
## 2 Protists &lt;tibble [888 × 18]&gt;   &lt;tibble [1 × 8]&gt;
## 3 Plants   &lt;tibble [1,304 × 18]&gt; &lt;tibble [1 × 8]&gt;
## 4 Fungi    &lt;tibble [6,064 × 18]&gt; &lt;tibble [1 × 8]&gt;
## 5 Animals  &lt;tibble [3,201 × 18]&gt; &lt;tibble [1 × 8]&gt;</code></pre>
<p>For at kunne se de statistics skal man bruge funktionen <code>unnest()</code> på variablen <code>test_stats</code>:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="visualising-trends.html#cb23-1" aria-hidden="true" tabindex="-1"></a>eukaryotes_cor <span class="ot">&lt;-</span> eukaryotes_cor <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="visualising-trends.html#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(test_stats)</span>
<span id="cb23-3"><a href="visualising-trends.html#cb23-3" aria-hidden="true" tabindex="-1"></a>eukaryotes_cor</span></code></pre></div>
<pre><code>## # A tibble: 5 × 10
## # Groups:   group [5]
##   group    data     estimate statistic   p.value parameter conf.low conf.high
##   &lt;chr&gt;    &lt;list&gt;      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;int&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 Other    &lt;tibble&gt;   0.489       3.80 4.22e-  4        46  0.238      0.679 
## 2 Protists &lt;tibble&gt;   0.301       9.26 1.54e- 19       860  0.239      0.361 
## 3 Plants   &lt;tibble&gt;  -0.203      -7.37 3.10e- 13      1267 -0.255     -0.149 
## 4 Fungi    &lt;tibble&gt;   0.377      31.2  3.87e-198      5884  0.355      0.399 
## 5 Animals  &lt;tibble&gt;   0.0437      2.42 1.57e-  2      3053  0.00825    0.0790
## # … with 2 more variables: method &lt;chr&gt;, alternative &lt;chr&gt;</code></pre>
<p>Vi kan bruge den direkte i et plot. Lad os fokusere på den korrelaton koefficient i kolonnen <code>estimate</code> og omsætte den til et plot:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="visualising-trends.html#cb25-1" aria-hidden="true" tabindex="-1"></a>cor_plot <span class="ot">&lt;-</span> eukaryotes_cor <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="visualising-trends.html#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>group,<span class="at">y=</span>estimate,<span class="at">fill=</span>group)) <span class="sc">+</span> </span>
<span id="cb25-3"><a href="visualising-trends.html#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">&quot;identity&quot;</span>,<span class="at">colour=</span><span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb25-4"><a href="visualising-trends.html#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">&quot;Set3&quot;</span>) <span class="sc">+</span> </span>
<span id="cb25-5"><a href="visualising-trends.html#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Corrlation estimate&quot;</span>) <span class="sc">+</span></span>
<span id="cb25-6"><a href="visualising-trends.html#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() </span>
<span id="cb25-7"><a href="visualising-trends.html#cb25-7" aria-hidden="true" tabindex="-1"></a>cor_plot</span></code></pre></div>
<p><img src="visualisering_22_files/figure-html/unnamed-chunk-13-1.png" width="384" /></p>
<p>Vi kan gå videre med vores plot og tilføje nogle labels efter p-værdien for at gøre det mere informativ - lad os først gå videre til at lave en lignende analyse med lineær regression.</p>
</div>
</div>
<div id="visualisering-af-lineær-regression-med-ggplot2" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> Visualisering af lineær regression med ggplot2<a href="visualising-trends.html#visualisering-af-lineær-regression-med-ggplot2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="lineær-trends" class="section level3 hasAnchor" number="8.3.1">
<h3><span class="header-section-number">8.3.1</span> Lineær trends<a href="visualising-trends.html#lineær-trends" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Man kan benytter lineær regression til at visualisere trends i de data. For eksempel kan man se i følgende scatter plot mellem <code>body_mass_g</code> og <code>bill_length_mm</code> i datasættet <code>penguins</code> at der er plottet en bedste rette linje igennem punkterne, som viser, at der er en postiv sammenhæng mellem de to variabler.</p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="visualisering_22_files/figure-html/unnamed-chunk-14-1.png" width="480" /></p>
<p>Den bedste rette linje har en formel <span class="math inline">\(y = a + bx\)</span>, hvor <span class="math inline">\(a\)</span> er den “intercept” og <span class="math inline">\(b\)</span> er den “slope” (hælde) af linjen. Idéen med simpel lineær regression er, at man gerne vil finde den bedste mulige værdier for <span class="math inline">\(a\)</span> og <span class="math inline">\(b\)</span> for at plotte ovenstående linje således, at afstanden mellem linjen og punkterne bliver minimeret. Uden at gå i detaljer om hvordan det beregnes, kan man bruger <code>lm</code> indenfor R til at finde den bedste rette linje. For eksempel:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="visualising-trends.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(bill_length_mm<span class="sc">~</span>body_mass_g,<span class="at">data=</span>penguins)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = bill_length_mm ~ body_mass_g, data = penguins)
## 
## Coefficients:
## (Intercept)  body_mass_g  
##   27.150722     0.004003</code></pre>
<p>Her kan man se, at den intercept er 27.15 og den slope er 0.004 - det betyder, at hvis <code>body_mass_g</code> stiger ved 1, så ville den forventet <code>bill_length_mm</code> stiger ved 0.004. Man kan således bruge linjen til at lave forudsigelser. For eksempel, hvis jeg vejede en ny pingvin og fandt ud af, at den vejede 5000 gramms, kunne jeg bruge min linje som den bedste gætte på dens bill længde:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="visualising-trends.html#cb29-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fl">27.150722</span> <span class="sc">+</span> <span class="fl">0.004003</span>  <span class="sc">*</span> <span class="dv">5000</span></span>
<span id="cb29-2"><a href="visualising-trends.html#cb29-2" aria-hidden="true" tabindex="-1"></a>y</span></code></pre></div>
<pre><code>## [1] 47.16572</code></pre>
<p>Så kan man se, jeg forventer en pingvin af 5000 g til at have en bill length af omkring 47.2 mm. Den kan også visualiseres i et plot:</p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="visualisering_22_files/figure-html/unnamed-chunk-17-1.png" width="480" /></p>
</div>
<div id="plotting-lineær-trend-lines-with-geom_smooth" class="section level3 hasAnchor" number="8.3.2">
<h3><span class="header-section-number">8.3.2</span> plotting lineær trend lines with <code>geom_smooth()</code><a href="visualising-trends.html#plotting-lineær-trend-lines-with-geom_smooth" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Indbygget i <code>ggplot2</code> er en funktion der hedder <code>geom_smooth()</code> som kan bruges til at tilføje den bedste rette linje til plottet. Man benytte den simpelthen ved at specificere <code>+ geom_smooth(method="lm")</code> indenfor plot kommando:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="visualising-trends.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins,<span class="fu">aes</span>(<span class="at">x=</span>body_mass_g,<span class="at">y=</span>bill_length_mm)) <span class="sc">+</span> </span>
<span id="cb32-2"><a href="visualising-trends.html#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb32-3"><a href="visualising-trends.html#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb32-4"><a href="visualising-trends.html#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>,<span class="at">se=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="visualisering_22_files/figure-html/unnamed-chunk-18-1.png" width="480" /></p>
<p>Det er nemt at bruge (bare tilføj en kode linje) og at man kan få en konfidensinterval med, hvis man gerne vil have den: i ovenstående plot specificeret jeg <code>se=FALSE</code> men hvis jeg angiv <code>se=TRUE</code> (default), får jeg følgende plot:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="visualising-trends.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins,<span class="fu">aes</span>(<span class="at">x=</span>body_mass_g,<span class="at">y=</span>bill_length_mm)) <span class="sc">+</span> </span>
<span id="cb34-2"><a href="visualising-trends.html#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb34-3"><a href="visualising-trends.html#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb34-4"><a href="visualising-trends.html#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>,<span class="at">se=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="visualisering_22_files/figure-html/unnamed-chunk-19-1.png" width="480" /></p>
</div>
<div id="plotting-multiple-lineær-trend-lines-with-geom_smooth" class="section level3 hasAnchor" number="8.3.3">
<h3><span class="header-section-number">8.3.3</span> plotting multiple lineær trend lines with <code>geom_smooth()</code><a href="visualising-trends.html#plotting-multiple-lineær-trend-lines-with-geom_smooth" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For at tilføje en bedste rette linje til hver af de tre <code>species</code> i stedet for samtlige data, er det meget nemt i <code>ggplot</code>: man angiver bare <code>colour=species</code>:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="visualising-trends.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins,<span class="fu">aes</span>(<span class="at">x=</span>body_mass_g,<span class="at">y=</span>bill_length_mm,<span class="at">colour=</span>species)) <span class="sc">+</span> </span>
<span id="cb36-2"><a href="visualising-trends.html#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb36-3"><a href="visualising-trends.html#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb36-4"><a href="visualising-trends.html#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>,<span class="at">se=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="visualisering_22_files/figure-html/unnamed-chunk-20-1.png" width="480" /></p>
<p>Så kan vi se, at der faktisk er tre forskellige trends her, så det giver god mening at bruge de tre forskellige linjer i stedet for kun en.</p>
</div>
<div id="plot-trends-med-methodloess-i-ggplot." class="section level3 hasAnchor" number="8.3.4">
<h3><span class="header-section-number">8.3.4</span> Plot trends med <code>method=="loess"</code> i ggplot.<a href="visualising-trends.html#plot-trends-med-methodloess-i-ggplot." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>I <code>ggplot</code> er vi ikke begrænset til <code>method="lm"</code> indenfor <code>geom_smooth()</code>. Lad os afpøve i stedet <code>method="loess"</code>:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="visualising-trends.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb38-2"><a href="visualising-trends.html#cb38-2" aria-hidden="true" tabindex="-1"></a>penguins <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(penguins)</span>
<span id="cb38-3"><a href="visualising-trends.html#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins,<span class="fu">aes</span>(<span class="at">x=</span>body_mass_g,<span class="at">y=</span>bill_length_mm,<span class="at">colour=</span>species)) <span class="sc">+</span> </span>
<span id="cb38-4"><a href="visualising-trends.html#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb38-5"><a href="visualising-trends.html#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb38-6"><a href="visualising-trends.html#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;loess&quot;</span>,<span class="at">se=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="visualisering_22_files/figure-html/unnamed-chunk-21-1.png" width="480" /></p>
<p>Så kan man fange trends som ikke nødvendigvis er lineær. Men det er mere ligefrem at beskrive en lineær trend og bruge den til at beregne de nødvendige statistik til at støtte vores observationer.</p>
</div>
</div>
<div id="plot-linear-regresion-estimates" class="section level2 hasAnchor" number="8.4">
<h2><span class="header-section-number">8.4</span> Plot linear regresion estimates<a href="visualising-trends.html#plot-linear-regresion-estimates" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For at finde vores estimates og tjekke signifikansen af de lineær trend, skal man arbejde direkte med den lineær model funktion <code>lm</code> som i ovenstående:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="visualising-trends.html#cb40-1" aria-hidden="true" tabindex="-1"></a>my.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(bill_length_mm<span class="sc">~</span>body_mass_g,<span class="at">data=</span>penguins)</span>
<span id="cb40-2"><a href="visualising-trends.html#cb40-2" aria-hidden="true" tabindex="-1"></a>my.lm</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = bill_length_mm ~ body_mass_g, data = penguins)
## 
## Coefficients:
## (Intercept)  body_mass_g  
##   27.150722     0.004003</code></pre>
<p>For at finde ud af den signifikans kan man kigge på <code>summary</code></p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="visualising-trends.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(my.lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = bill_length_mm ~ body_mass_g, data = penguins)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -10.1652  -3.0664  -0.7672   2.2356  16.0371 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 2.715e+01  1.292e+00   21.02   &lt;2e-16 ***
## body_mass_g 4.003e-03  3.016e-04   13.28   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.424 on 331 degrees of freedom
## Multiple R-squared:  0.3475, Adjusted R-squared:  0.3455 
## F-statistic: 176.2 on 1 and 331 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>De tal, som er vigtige her:</p>
<ul>
<li>Den p-værdi: <code>&lt;2e-16</code> - den trend er statistiske signifikant.</li>
<li>Den R-squared værdi - det viser den proportion af variancen i <code>bill_length_mm</code> som <code>body_mass_g</code> forklarer. Det er svarende til den korrelation koefficient squared og kan fortolkes således -
<ul>
<li>hvis R-squared er tæt på 1, så er der tæt på en perfekt korrespondens mellem <code>bill_length_mm</code> og <code>body_mass_g</code>.</li>
<li>hvis R-squared er tæt på 0, så er der nærmeste ingen korrespondens.</li>
</ul></li>
</ul>
<div id="iteratively-estimating-multiple-trends" class="section level3 hasAnchor" number="8.4.1">
<h3><span class="header-section-number">8.4.1</span> Iteratively estimating multiple trends<a href="visualising-trends.html#iteratively-estimating-multiple-trends" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Vi kan benytte de koncepter som vi lært i sidste lektion, og som er samme som ovenpå i vores korrelation analyse.</p>
<p>Vi vil gerne lave en model med <code>lm</code> som ovenpå, og vi tilføje <code>glance()</code> til at få de model statistikker i en pæn form.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="visualising-trends.html#cb44-1" aria-hidden="true" tabindex="-1"></a>lm_model_func <span class="ot">&lt;-</span> <span class="er">~</span><span class="fu">lm</span>(bill_length_mm<span class="sc">~</span>body_mass_g,<span class="at">data=</span>.x) <span class="sc">%&gt;%</span> <span class="fu">glance</span>()</span></code></pre></div>
<p>Vi bruge <code>group_by</code> til at opdele efter de tre <code>species</code> og så nest de tre datarammer:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="visualising-trends.html#cb45-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">%&gt;%</span> </span>
<span id="cb45-2"><a href="visualising-trends.html#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(species) <span class="sc">%&gt;%</span></span>
<span id="cb45-3"><a href="visualising-trends.html#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>()</span></code></pre></div>
<pre><code>## # A tibble: 3 × 2
## # Groups:   species [3]
##   species   data              
##   &lt;fct&gt;     &lt;list&gt;            
## 1 Adelie    &lt;tibble [146 × 7]&gt;
## 2 Gentoo    &lt;tibble [119 × 7]&gt;
## 3 Chinstrap &lt;tibble [68 × 7]&gt;</code></pre>
<p>Vi lave en lineær model på hver af de tre datasæt med <code>map</code> og ved at specifice funktion som vi defineret ovenpå. Vi bruger <code>mutate</code> ligesom før til at tilføje resulterende statistikker som en ny kolon der hedder <code>lm_stats</code>:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="visualising-trends.html#cb47-1" aria-hidden="true" tabindex="-1"></a>penguins_lm <span class="ot">&lt;-</span> penguins <span class="sc">%&gt;%</span> </span>
<span id="cb47-2"><a href="visualising-trends.html#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(species) <span class="sc">%&gt;%</span></span>
<span id="cb47-3"><a href="visualising-trends.html#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb47-4"><a href="visualising-trends.html#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb47-5"><a href="visualising-trends.html#cb47-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">lm_stats=</span><span class="fu">map</span>(data,lm_model_func),</span>
<span id="cb47-6"><a href="visualising-trends.html#cb47-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb47-7"><a href="visualising-trends.html#cb47-7" aria-hidden="true" tabindex="-1"></a>penguins_lm</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
## # Groups:   species [3]
##   species   data               lm_stats         
##   &lt;fct&gt;     &lt;list&gt;             &lt;list&gt;           
## 1 Adelie    &lt;tibble [146 × 7]&gt; &lt;tibble [1 × 12]&gt;
## 2 Gentoo    &lt;tibble [119 × 7]&gt; &lt;tibble [1 × 12]&gt;
## 3 Chinstrap &lt;tibble [68 × 7]&gt;  &lt;tibble [1 × 12]&gt;</code></pre>
<p>Til sidste bruger vi funkction <code>unnest</code> på vores statistikker:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="visualising-trends.html#cb49-1" aria-hidden="true" tabindex="-1"></a>penguins_lm <span class="ot">&lt;-</span> penguins_lm <span class="sc">%&gt;%</span></span>
<span id="cb49-2"><a href="visualising-trends.html#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(<span class="at">cols=</span>lm_stats)</span>
<span id="cb49-3"><a href="visualising-trends.html#cb49-3" aria-hidden="true" tabindex="-1"></a>penguins_lm</span></code></pre></div>
<pre><code>## # A tibble: 3 × 14
## # Groups:   species [3]
##   species data     r.squared adj.r.squared sigma statistic  p.value    df logLik
##   &lt;fct&gt;   &lt;list&gt;       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1 Adelie  &lt;tibble&gt;     0.296         0.291  2.24      60.6 1.24e-12     1  -324.
## 2 Gentoo  &lt;tibble&gt;     0.445         0.440  2.32      93.6 1.26e-16     1  -268.
## 3 Chinst… &lt;tibble&gt;     0.264         0.253  2.89      23.7 7.48e- 6     1  -168.
## # … with 5 more variables: AIC &lt;dbl&gt;, BIC &lt;dbl&gt;, deviance &lt;dbl&gt;,
## #   df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
<!-- ```{r} -->
<!-- penguins_lm <- penguins %>%  -->
<!--   group_by(species) %>% -->
<!--   nest() %>% -->
<!--   mutate(lm_model = map(data,~lm(bill_length_mm~body_mass_g,data=.x))) %>% -->
<!--   mutate( -->
<!--          lm_intercept = map_dbl(lm_model,~.x$coefficients[1]), #intercept -->
<!--          lm_slope = map_dbl(lm_model,~.x$coefficients[2]), #slope -->
<!--          lm_pval = map_dbl(lm_model,~summary(.x)$coefficients[2,4]), #slope signifikans -->
<!--          lm_rsquared = map_dbl(lm_model,~summary(.x)$r.squared) #rsquared -->
<!--         ) -->
<!-- penguins_lm -->
<!-- ``` -->
<p>Så kan vi se, at vi har fået en dataramme med vores lineær model statistics. Lad os omsætte dem til et plot for at sammenligne dem over de tre <code>species</code> af pingvin.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="visualising-trends.html#cb51-1" aria-hidden="true" tabindex="-1"></a>penguins_lm <span class="sc">%&gt;%</span> </span>
<span id="cb51-2"><a href="visualising-trends.html#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(species,r.squared,p.value) <span class="sc">%&gt;%</span></span>
<span id="cb51-3"><a href="visualising-trends.html#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">&quot;-log10pval&quot;</span> <span class="ot">=</span> <span class="sc">-</span><span class="fu">log10</span>(p.value)) <span class="sc">%&gt;%</span></span>
<span id="cb51-4"><a href="visualising-trends.html#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>p.value) <span class="sc">%&gt;%</span></span>
<span id="cb51-5"><a href="visualising-trends.html#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>species) <span class="sc">%&gt;%</span></span>
<span id="cb51-6"><a href="visualising-trends.html#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>species,<span class="at">y=</span>value,<span class="at">fill=</span>species)) <span class="sc">+</span> </span>
<span id="cb51-7"><a href="visualising-trends.html#cb51-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">&quot;identity&quot;</span>) <span class="sc">+</span> </span>
<span id="cb51-8"><a href="visualising-trends.html#cb51-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">&quot;Set2&quot;</span>) <span class="sc">+</span></span>
<span id="cb51-9"><a href="visualising-trends.html#cb51-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>name,<span class="at">scale=</span><span class="st">&quot;free&quot;</span>,<span class="at">ncol=</span><span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb51-10"><a href="visualising-trends.html#cb51-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="visualisering_22_files/figure-html/unnamed-chunk-28-1.png" width="768" /></p>
</div>
<div id="lave-og-tilføje-labels-til-dit-regression-plot" class="section level3 hasAnchor" number="8.4.2">
<h3><span class="header-section-number">8.4.2</span> Lave og tilføje labels til dit regression plot<a href="visualising-trends.html#lave-og-tilføje-labels-til-dit-regression-plot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Som nævnt tidligere, kan det være nyttig at tilføje nogle labels til vores plots med de statistikker, vi lige har beregnet. I tilfældet af vores lineær regression trend lines, vi vil gerne tilføje de r-squared værdier og de p-værdier.</p>
<p>Til at gøre det kan man bruge følgende kode. Vi tage vores datasæt <code>penguins_lm</code> med vores beregnet statistikker og bruge den til at lave en datasæt som kan bruges i <code>geom_text()</code> i vores trend plot. Funktionen <code>glue()</code> (fra pakken <code>glue()</code>) er bare en nyttig måde at tilføj de <code>r.squared</code> og <code>p.value</code> værdier sammen i en string som beskriver vores forskellige trends</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="visualising-trends.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glue)  <span class="co"># for putting the values together in a label</span></span>
<span id="cb52-2"><a href="visualising-trends.html#cb52-2" aria-hidden="true" tabindex="-1"></a>label_data <span class="ot">&lt;-</span> penguins_lm <span class="sc">%&gt;%</span></span>
<span id="cb52-3"><a href="visualising-trends.html#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb52-4"><a href="visualising-trends.html#cb52-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">rsqr =</span> <span class="fu">signif</span>(r.squared, <span class="dv">2</span>),  <span class="co"># round to 2 significant digits</span></span>
<span id="cb52-5"><a href="visualising-trends.html#cb52-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">pval =</span> <span class="fu">signif</span>(p.value, <span class="dv">2</span>),</span>
<span id="cb52-6"><a href="visualising-trends.html#cb52-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">label =</span> <span class="fu">glue</span>(<span class="st">&quot;r^2 = {rsqr}, p-value = {pval}&quot;</span>)</span>
<span id="cb52-7"><a href="visualising-trends.html#cb52-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb52-8"><a href="visualising-trends.html#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(species, label)</span>
<span id="cb52-9"><a href="visualising-trends.html#cb52-9" aria-hidden="true" tabindex="-1"></a>label_data</span></code></pre></div>
<pre><code>FALSE # A tibble: 3 × 2
FALSE # Groups:   species [3]
FALSE   species   label                        
FALSE   &lt;fct&gt;     &lt;glue&gt;                       
FALSE 1 Adelie    r^2 = 0.3, p-value = 1.2e-12 
FALSE 2 Gentoo    r^2 = 0.44, p-value = 1.3e-16
FALSE 3 Chinstrap r^2 = 0.26, p-value = 7.5e-06</code></pre>
<p>Vi kan tilføje vores label data indenfor <code>geom_text()</code>. <code>x</code> og <code>y</code> specificere hvor i plottet teksten skal være, og husk at specificere <code>data=label_data</code> og <code>label=label</code> skal stå indenfor <code>aes()</code> når det handler om en variable i <code>label_data</code>.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="visualising-trends.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penguins, <span class="fu">aes</span>(body_mass_g, flipper_length_mm, <span class="at">colour=</span>species)) <span class="sc">+</span> </span>
<span id="cb54-2"><a href="visualising-trends.html#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb54-3"><a href="visualising-trends.html#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb54-4"><a href="visualising-trends.html#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb54-5"><a href="visualising-trends.html#cb54-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="dv">5500</span>, </span>
<span id="cb54-6"><a href="visualising-trends.html#cb54-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">175</span>,<span class="dv">180</span>,<span class="dv">185</span>),</span>
<span id="cb54-7"><a href="visualising-trends.html#cb54-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> label_data, <span class="fu">aes</span>(<span class="at">label =</span> label), <span class="co">#specify label data from above</span></span>
<span id="cb54-8"><a href="visualising-trends.html#cb54-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">4</span></span>
<span id="cb54-9"><a href="visualising-trends.html#cb54-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb54-10"><a href="visualising-trends.html#cb54-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">&quot;Set2&quot;</span>) <span class="sc">+</span></span>
<span id="cb54-11"><a href="visualising-trends.html#cb54-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() </span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="visualisering_22_files/figure-html/unnamed-chunk-30-1.png" width="576" /></p>
</div>
<div id="case_when-adding-bar-plot-text" class="section level3 hasAnchor" number="8.4.3">
<h3><span class="header-section-number">8.4.3</span> <code>case_when()</code>: adding bar plot text<a href="visualising-trends.html#case_when-adding-bar-plot-text" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Det vil også være rart at tilføje vores p-værdier i vores barplot fra ovenstående korrelation analyse. Den kan laves igen med <code>geom_text</code>. Husk at vi bruge lokale aethetics funktion <code>aes()</code> indenfor <code>geom_text()</code>. Her specificerer vi at parameteren <code>label</code> skal være vores p-værdier fra vores datasæt. Parameteren <code>vjust</code> bruges til at få de tal lidt ovenpå søjlerne.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="visualising-trends.html#cb56-1" aria-hidden="true" tabindex="-1"></a>cor_plot <span class="sc">+</span> </span>
<span id="cb56-2"><a href="visualising-trends.html#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">round</span>(p.value,<span class="dv">3</span>)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>)</span></code></pre></div>
<p><img src="visualisering_22_files/figure-html/unnamed-chunk-31-1.png" width="384" /></p>
<p>Lad os transformere de p-værdi kolon til en der viser signifikans i formen af stjerne (det ses meget ofte indenfor præsentationer og publikationer). Her kan man bruge <code>case_when</code> - det ligner <code>ifelse</code> men kan benyttes i tilfældet hvor der er flere en to muligheder. Man angiver de forskellige muligheder og separerer hvad sker hvis <code>TRUE</code> med tilde (for eksempel hvis p-værdien er mindre end 0.001 så få kolonnen <code>sig</code> tre stjerne). Her er <code>p.value &lt; 0.001</code> skrev i linjen før <code>p.value &lt; 0.01</code> så dette tilfælde få prioritet (hvis p-værdien er mindre end 0.001 få <code>sig</code> så tre stjerner i stedet for to).</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="visualising-trends.html#cb57-1" aria-hidden="true" tabindex="-1"></a>eukaryotes_cor_sig <span class="ot">&lt;-</span> eukaryotes_cor <span class="sc">%&gt;%</span></span>
<span id="cb57-2"><a href="visualising-trends.html#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>data) <span class="sc">%&gt;%</span> </span>
<span id="cb57-3"><a href="visualising-trends.html#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sig =</span> <span class="fu">case_when</span>(p.value <span class="sc">&lt;</span> <span class="fl">0.001</span> <span class="sc">~</span> <span class="st">&quot;***&quot;</span>,</span>
<span id="cb57-4"><a href="visualising-trends.html#cb57-4" aria-hidden="true" tabindex="-1"></a>                         p.value <span class="sc">&lt;</span> <span class="fl">0.01</span> <span class="sc">~</span> <span class="st">&quot;**&quot;</span>,</span>
<span id="cb57-5"><a href="visualising-trends.html#cb57-5" aria-hidden="true" tabindex="-1"></a>                         p.value <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="sc">~</span> <span class="st">&quot;*&quot;</span>,</span>
<span id="cb57-6"><a href="visualising-trends.html#cb57-6" aria-hidden="true" tabindex="-1"></a>                         p.value <span class="sc">&lt;</span> <span class="fl">0.1</span> <span class="sc">~</span> <span class="st">&quot;.&quot;</span>,</span>
<span id="cb57-7"><a href="visualising-trends.html#cb57-7" aria-hidden="true" tabindex="-1"></a>                         p.value <span class="sc">&gt;=</span> <span class="fl">0.1</span> <span class="sc">~</span> <span class="st">&quot;n.s&quot;</span>))</span>
<span id="cb57-8"><a href="visualising-trends.html#cb57-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-9"><a href="visualising-trends.html#cb57-9" aria-hidden="true" tabindex="-1"></a>eukaryotes_cor_sig <span class="sc">%&gt;%</span> <span class="fu">select</span>(group,sig) <span class="co">#viser hvordan det ser ud</span></span></code></pre></div>
<pre><code>## # A tibble: 5 × 2
## # Groups:   group [5]
##   group    sig  
##   &lt;chr&gt;    &lt;chr&gt;
## 1 Other    ***  
## 2 Protists ***  
## 3 Plants   ***  
## 4 Fungi    ***  
## 5 Animals  *</code></pre>
<p>Nu at vi har fået en ny kolon der hedder <code>sig</code> kan det anvendes indenfor <code>geom_text</code> som i forudgående plot.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="visualising-trends.html#cb59-1" aria-hidden="true" tabindex="-1"></a>cor_plot <span class="ot">&lt;-</span> eukaryotes_cor_sig <span class="sc">%&gt;%</span></span>
<span id="cb59-2"><a href="visualising-trends.html#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>group,<span class="at">y=</span>estimate,<span class="at">fill=</span>group)) <span class="sc">+</span> </span>
<span id="cb59-3"><a href="visualising-trends.html#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">&quot;identity&quot;</span>,<span class="at">colour=</span><span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb59-4"><a href="visualising-trends.html#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">&quot;Set3&quot;</span>) <span class="sc">+</span> </span>
<span id="cb59-5"><a href="visualising-trends.html#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Corrlation estimate&quot;</span>) <span class="sc">+</span></span>
<span id="cb59-6"><a href="visualising-trends.html#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()  <span class="sc">+</span> </span>
<span id="cb59-7"><a href="visualising-trends.html#cb59-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> sig),<span class="at">size=</span><span class="dv">5</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.1</span>)</span>
<span id="cb59-8"><a href="visualising-trends.html#cb59-8" aria-hidden="true" tabindex="-1"></a>cor_plot</span></code></pre></div>
<p><img src="visualisering_22_files/figure-html/unnamed-chunk-33-1.png" width="384" /></p>
<p>Mere om adding labels to barplots: <a href="https://r-graphics.org/recipe-bar-graph-labels" class="uri">https://r-graphics.org/recipe-bar-graph-labels</a></p>
</div>
</div>
<div id="problemstillinger-7" class="section level2 hasAnchor" number="8.5">
<h2><span class="header-section-number">8.5</span> Problemstillinger<a href="visualising-trends.html#problemstillinger-7" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>0</strong>) Quizzen på Absalon.</p>
<p>Husk at have indlæste følgende:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="visualising-trends.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb60-2"><a href="visualising-trends.html#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb60-3"><a href="visualising-trends.html#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb60-4"><a href="visualising-trends.html#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(iris)</span></code></pre></div>
<p><strong>1</strong>) <em>Korrelation øvelse</em></p>
<ul>
<li><p>Brug <code>data(mtcars)</code> og <code>cor.test()</code> til at lave et test af korrelationen mellem variablerne <code>qsec</code> og <code>drat</code>.</p></li>
<li><p>Tip: hvis du foretrækker at undgå <code>$</code> i analysen til at speciefice en kolon indenfor <code>cor.test()</code> kan du bruge <code>mtcars %&gt;% pull(qsec)</code> i stedet for <code>mtcars$qsec</code>.</p></li>
<li><p>Tilføj funktionen <code>glance()</code> til din resultat fra <code>cor.test()</code> til at se de statistikker i <strong>tidy</strong> form. Kan du genkende de statistikker fra <code>cor.test()</code> i den resulterende dataramme?</p></li>
</ul>
<p><strong>2</strong>) <em>Korrelation øvelse</em></p>
<p>Vælg <code>Species</code> <code>setosa</code> fra <code>iris</code> (<code>data(iris)</code>) og brug <code>cor.test()</code> til at beregne korrelationen mellem <code>Sepal.Width</code> og <code>Sepal.Length</code>.</p>
<ul>
<li>Angiv resultaterne i <strong>tidy</strong> form.</li>
</ul>
<p><strong>3</strong>) <em>Nesting øvelse</em></p>
<p>For datasættet <code>mtcars</code> anvende <code>group_by()</code> og <code>nest()</code> til at få en nested datasæt opdelt efter variablen <code>cyl</code>.</p>
<ul>
<li><p>Hvor mange datasæt har du fået indenfor kolonnen <code>data</code>?</p></li>
<li><p>Tilføj en ny kolon med <code>mutate</code> der hedder <code>n_rows</code> som beregner antallet af række i hver af de tre datasæt - brug følgende struktur (først angiv kolonnen som indeholder vores list af datasæt, og så angive funktionen som beregner antallet af række).</p></li>
</ul>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="visualising-trends.html#cb61-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb61-2"><a href="visualising-trends.html#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cyl) <span class="sc">%&gt;%</span> </span>
<span id="cb61-3"><a href="visualising-trends.html#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>() <span class="sc">%&gt;%</span></span>
<span id="cb61-4"><a href="visualising-trends.html#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">&quot;n_rows&quot;</span> <span class="ot">=</span> <span class="fu">map</span>(???,???)) <span class="co">#erstatte ??? her</span></span></code></pre></div>
<ul>
<li>Hvad få du indenfor din ny kolonnen? Prøve at andre <code>map</code> til <code>map_dbl</code> og se hvad der sker.</li>
<li>Beholde <code>map</code> og tilføj <code>%&gt;% unnest(n_rows)</code> i stedet for og se hvad der sker.</li>
</ul>
<p><strong>4</strong>) <em>Multiple korrelation</em></p>
<p>Vi vil gerne beregne den korrelation mellem variablerne <code>qsec</code> og <code>drat</code> til hver af de tre datasæt.</p>
<ul>
<li>Tilpasse følgende funktion så at vi teste korrelation mellem de to variabler.</li>
<li>Tilføje <code>glance()</code> så at vi få vores data i <strong>tidy</strong> form.</li>
</ul>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="visualising-trends.html#cb62-1" aria-hidden="true" tabindex="-1"></a>cor_test <span class="ot">&lt;-</span> <span class="er">~</span><span class="fu">cor.test</span>(.x<span class="sc">$</span>qsec,???) <span class="co">#erstatte ??? og tilføj glance funktion</span></span></code></pre></div>
<ul>
<li>Brug map i nedenstående med din funktion til at beregne de korrelation til hver af de tre datasæt.</li>
<li>Huske at <code>unnest</code> kolonnen med dine korrelation statistikker bagefter.</li>
</ul>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="visualising-trends.html#cb63-1" aria-hidden="true" tabindex="-1"></a>mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb63-2"><a href="visualising-trends.html#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cyl) <span class="sc">%&gt;%</span> </span>
<span id="cb63-3"><a href="visualising-trends.html#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nest</span>() <span class="sc">%&gt;%</span></span>
<span id="cb63-4"><a href="visualising-trends.html#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cor_stats =</span> ???) <span class="co">#erstatte ??? her og husk unnest</span></span></code></pre></div>
<ul>
<li>Lave et barplot af <code>estimate</code> med den resulterende dataramme</li>
</ul>
<p><strong>5</strong>) <em>Multiple korrelation øvelse</em></p>
<p>Lave samme analyse som <strong>4</strong>) men</p>
<ul>
<li>nest de data efter <code>gear</code></li>
<li>beregne korrelationen mellem <code>wt</code> og <code>drat</code></li>
</ul>
<p><strong>6</strong>) <em>Linear regression øvelse</em></p>
<p>Brug <code>data(iris)</code> og anvende <code>lm()</code> til at finde den forventet <code>Petal.Length</code> med hensyn til <code>Petal.Width</code>.</p>
<ul>
<li>Hvad er den intercept og slope af den beregnet linje?</li>
<li>Tilføj funktionen <code>glance()</code> og angive værdier <code>r.squared</code> og <code>p.value</code>.</li>
</ul>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="visualising-trends.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(??? <span class="sc">~</span> ???,<span class="at">data=</span>???) <span class="co">#erstatte ???</span></span></code></pre></div>
<p><strong>7</strong>) Lave et scatter plot af Petal.Width på x-aksen og Petal.Length på y-aksen.</p>
<ul>
<li>Tilføje linjen <code>geom_smooth(method="smooth")</code></li>
<li>Ændre linjen til <code>geom_smooth(method="lm")</code></li>
<li>Ændre linjen til <code>geom_smooth(method="lm",se=FALSE)</code></li>
<li>Nu specificer en forskellige farve efter Species. Er der forskellige trends?</li>
</ul>
<p>Vi vil gerne lave samme analyse for hver af de tre Species.</p>
<p><strong>8</strong>) <em>Lineær regression øvelse over multiple datasæt</em></p>
<p>Vi vil gerne udføre lineær regression med Petal.Length og Petal.Width som i <strong>6</strong>), men opdelt efter de tre Species.
* Lave en funktion ved at tilpasse følgende kode. Passe på hvad <code>data</code> skal være lig med her (når vi skriver en funktion).
* Tilføj <code>glance()</code>.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="visualising-trends.html#cb65-1" aria-hidden="true" tabindex="-1"></a>lm_model_func <span class="ot">&lt;-</span> ???<span class="fu">lm</span>(??? <span class="sc">~</span> ???,<span class="at">data=</span>???) <span class="co">#erstat ??? </span></span></code></pre></div>
<ul>
<li>Anvende <code>group_by()</code> og <code>nest()</code></li>
<li>Anvende <code>map()</code> med din funktion indenfor <code>mutate()</code> til at tilføje en ny kolon som hedder <code>lm_stats</code> til din dataramme.</li>
<li>Husk at <code>unnest</code> kolonnen <code>lm_stats</code>til at kunne se statistikker.</li>
</ul>
<p><strong>9</strong>) <em>Tilføj statistik til plottet</em></p>
<p>Vi vil gerne tilføj de statistikker vi lige har beregnet i <strong>8</strong>) til plottet vi lavet i <strong>7</strong>).</p>
<p>Kopiere koden fra sektionen “Lave og tilføje labels til dit regression plot” og tilpasse den til din analyse med <code>iris</code>.</p>
<p><strong>10</strong>) <em>Tilføj statistik til plottet</em></p>
<p>Vi vil gerne tilføj de statistikker vi lige har beregnet i <strong>4</strong>) til et bar plot af vores korrelation estimates.</p>
<p>Kopiere koden fra sektionen “<code>case_when()</code>: adding bar plot text” og tilpasse den til din analyse med <code>mtcars</code>.</p>
</div>
<div id="næste-uge" class="section level2 hasAnchor" number="8.6">
<h2><span class="header-section-number">8.6</span> Næste uge<a href="visualising-trends.html#næste-uge" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Clustering af data ind i forskellige grupper - kmeans/hierarchical clustering (kun undervisning på tirsdag og workshop på fredag).</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="forbine-tables-iterations-og-funktioner.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["visualisering_22.pdf", "visualisering_22.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
